function info = smpm_fieldfile_info( field_file_name, version )
% info = smpm_fieldfile_info( field_file_name )
%
% Reads the contents of the field file generated by the SMPM solver code, and
% returns some information about the field file.
%
% Takes 1 argument:
%
%   field_file_name - String indicating the field file to read from disk.
%
% Returns 1 value:
%
%   info - Structure containing the following fields:
%
%     .n  - Number of collocation points.
%     .mx - Number of sub-domains in the X-dimension.
%     .my - Number of sub-domains in the Y-dimension.
%     .mz - Number of sub-domains in the Z-dimension.
%     .x  - Matrix, sized (mz*n)x(mx*n)x(my), of x-coordinates.
%     .y  - Matrix, sized (mz*n)x(mx*n)x(my), of y-coordinates.
%     .z  - Matrix, sized (mz*n)x(mx*n)x(my), of z-coordinates.
%

% Read the grid information and the grid.
info.n  = h5read( field_file_name, '/grid/n' );
info.mx = h5read( field_file_name, '/grid/mx' );
info.my = h5read( field_file_name, '/grid/my' );
info.mz = h5read( field_file_name, '/grid/mz' );
info.x  = h5read( field_file_name, '/grid/x' );
info.y  = h5read( field_file_name, '/grid/y' );
info.z  = h5read( field_file_name, '/grid/z' );

if version == 'OLD'
    % Figure out how many time-steps are in the file.
    info.number_steps = h5read( field_file_name, '/field/number_steps' );
end

end
