function configuration = smpm_read_configuration( field_file_name )
% configuration = smpm_read_configuration( field_file_name[, indexes] )
%
% Reads the contents of the field file generated by the SMPM solver code.
%
% Takes 1 argument:
%
%   field_file_name - String indicating the field file to read from disk.
%
% Returns 1 value:
%
%   configuration - Structure containing the fields described below:
%
%     .configuration.delta_t         - Timestep size of the run
%     .configuration.facrobin        - Factor used for penalty term 
%                                      in viscous equation.
%     .configuration.facrobin_ppe    - Factor used for penalty term 
%                                      in poisson equation.
%     .configuration.filter_order_xz - Filter order in GLL Grid (x-z)
%     .configuration.filter_order_y  - Filter order in periodic grid
%                                      (y).
%     .configuration.gmres_poisson_max_iterations- 
%                                    - Maximum poisson iterations for
%                                      pressure solve.
%     .configuration.poisson_restart - Maximum iterations for pressure
%                                      solve restart.
%     .configuration.poisson_tolerance-
%                                    - Minimum tolerance used for 
%                                      pressure solve.
%     .configuration.viscous_max_iterations-
%                                    - Maximum viscous iterations
%     .configuration.viscous_tolerance
%                                    - Minimum tolerance used for viscous
%                                      solve.
%     .configuration.steps_per_write - timesteps per fieldfile output
%     .configuration.time_treshold   - Total simulation time
%     .configuration.uC              - The left kernel vector of the 
%                                      capacitance matrix for the poisson
%                                      operator.
%     .configuration.uL              - The left kernel vector of the 
%                                      poisson operator.
%     .configuration.viscosity       - The kinematic viscosity of the fluid.
%
%  28 May 2017
%  Gustavo Rivera w/ Greg Thomsen & Sumedh Joshi

% Get the information
configuration.delta_t          = h5read( field_file_name, '/configuration/delta_t' );
configuration.facrobin         = h5read( field_file_name, '/configuration/facrobin' );
configuration.facrobin_ppe     = h5read( field_file_name, '/configuration/facrobin_ppe' );
configuration.filter_order_xz  = h5read( field_file_name, '/configuration/filter_order_xz' );
configuration.filter_order_y   = h5read( field_file_name, '/configuration/filter_order_y' );
configuration.gmres.poisson_max_iterations  = h5read( field_file_name, '/configuration/gmres/poisson_max_iterations' );
configuration.gmres.poisson_restart  = h5read( field_file_name, '/configuration/gmres/poisson_restart' );
configuration.gmres.poisson_tolerance  = h5read( field_file_name, '/configuration/gmres/poisson_tolerance' );
configuration.gmres.viscous_max_iterations  = h5read( field_file_name, '/configuration/gmres/viscous_max_iterations' );
configuration.gmres.viscous_tolerance  = h5read( field_file_name, '/configuration/gmres/viscous_tolerance' );
configuration.steps_per_write  = h5read( field_file_name, '/configuration/steps_per_write' );
configuration.time_threshold  = h5read( field_file_name, '/configuration/time_threshold' );
configuration.uC  = h5read( field_file_name, '/configuration/uC' );
configuration.uL  = h5read( field_file_name, '/configuration/uL' );
configuration.viscosity  = h5read( field_file_name, '/configuration/viscosity' );
end
