function execution = smpm_read_execution( field_file_name )
% execution = smpm_read_execution( field_file_name )
%
% Reads the contents of the field file, generated by the SMPM solver code,
% that pertain to the execution of the solver, not the field variables.
%
% Takes 1 argument:
%
%   field_file_name - String indicating the field file to read from disk.
%
% Returns 1 value:
%
%   execution - Structure containing the fields, at every timestep,
%               described below
%
%      Related to the CFL computation
%
%     ...cfl.cfl_x           - Max CFL number in the x-direction.
%     ...cfl.cfl_y           - Max CFL number in the y-direction.
%     ...cfl.cfl_z           - Max CFL number in the z-direction.
%     ...cfl.simulation_time - Simulation time at each step.
%     ...cfl.time_step_size  - Current Time step size
%     ...cfl.cpu_time        - Total CPU time (each rank)
%
%     Related to the error of iterative and linear system solvers
%
%     ...error.gmres_diffusion_iterations_imag
%                                - Total diffusion iterations for imag
%                                solve
%     ...error.gmres_diffusion_iterations_real
%                                - Total diffusion iterations for real
%                                solve
%     ...error.gmres_poisson_iterations_imag
%                                - Total poisson iterations for imag
%                                solve
%     ...error.gmres_poisson_iterations_real
%                                - Total poisson iterations for real
%                                solve
%     ...error.gmres_viscous_iterations_imag
%                                - Total poisson iterations for imag
%                                solve
%     ...error.gmres_poisson_iterations_real
%                                - Total poisson iterations for real
%                                solve
%     ...error.l2_poisson
%                                - error on pressure solve
%     ...error.l2_poisson_kernel
%                                - error on poisson kernel computation
%     ...error.l2_poisson_schur_imag
%                                - error on poisson imaginary solve
%     ...error.l2_poisson_schur_real
%                                - error on poisson real solve
%     ...error.l2_poisson_schur_kernel
%                                - error on Schur kernel
%     ...error.linf_diffusion_imag
%                                - error on diffusion imag solve
%     ...error.linf_diffusion_real
%                                - error on diffusion real solve
%     ...error.linf_divergence
%                                - error on divergence
%     ...error.linf_viscous_imag
%                                - error on viscous imag solve
%     ...error.linf_diffusion_real
%                                - error on viscous real solve
%     ...error.total_norm_numeric_error
%                                - total numeric error in solver
%
%     Related to amount of workers and dimensions used for simulation
%
%     ...cpu_time        - total CPU time for simulation
%     ...number_ranks    - number of ranks in simulation
%     ...number_threads  - number of threads in simulation
%
%     Related to wall clock time
%
%     ...wall_time.field_io        - total wall time for field I/O
%     ...wall_time.restart_io      - total wall time for restart I/O
%     ...wall_time.null_basis      - total wall time for null basis
%                                    calculation
%     ...wall_time.null_error      - total wall time for null error
%                                    calculation
%     ...wall_time.solve_poisson   - total time spent solving poisson
%                                    equation
%     ...wall_time.setup           - total wall time for setup
%     ...wall_time.solve_diffusion - total time spent solving diffusion
%                                    equation
%     ...wall_time.solve_viscous   - total time spent solving viscous
%                                    equation
%     ...wall_time.start           - when did SMPM actually start
%     ...wall_time.steps           - total wall time per time step
%     ...wall_time.total           - total wall time for simulation
%
%  28 May 2017
%  Gustavo Rivera w/ Greg Thomsen & Sumedh Joshi

% Read CFL-Related Data
execution.cfl.cfl_x           = h5read( field_file_name, ...
    '/execution/cfl/cfl_x' );
execution.cfl.cfl_y           = h5read( field_file_name, ...
    '/execution/cfl/cfl_y' );
execution.cfl.cfl_z           = h5read( field_file_name, ...
    '/execution/cfl/cfl_z' );
execution.cfl.simulation_time = h5read( field_file_name, ...
    '/execution/cfl/simulation_time' );
execution.cfl.time_step_size  = h5read( field_file_name, ...
    '/execution/cfl/time_step_size' );

% Read Other-Related Data
execution.cpu_time       = h5read( field_file_name, ...
    '/execution/cpu_time' );
execution.number_ranks   = h5read( field_file_name, ...
    '/execution/number_ranks' );
execution.number_threads = h5read( field_file_name, ...
    '/execution/number_threads' );

% Read error-related data
execution.error.gmres_diffusion_iterations_imag  ...
    = h5read( field_file_name, ...
    '/execution/error/gmres_diffusion_iterations_imag' );
execution.error.gmres_diffusion_iterations_real  ...
    = h5read( field_file_name, ...
    '/execution/error/gmres_diffusion_iterations_real' );
execution.error.gmres_poisson_iterations_imag  ...
    = h5read( field_file_name, ...
    '/execution/error/gmres_poisson_iterations_imag' );
execution.error.gmres_poisson_iterations_real  ...
    = h5read( field_file_name, ...
    '/execution/error/gmres_poisson_iterations_real' );
execution.error.gmres_viscous_iterations_imag  ...
    = h5read( field_file_name, ...
    '/execution/error/gmres_viscous_iterations_imag' );
execution.error.gmres_viscous_iterations_real  ...
    = h5read( field_file_name, ...
    '/execution/error/gmres_viscous_iterations_real' );
execution.error.l2_poisson  = h5read( field_file_name, ...
    '/execution/error/l2_poisson' );
execution.error.l2_poisson_kernel  = h5read( field_file_name, ...
    '/execution/error/l2_poisson_kernel' );
execution.error.l2_poisson_schur_imag ...
    = h5read( field_file_name, ...
    '/execution/error/l2_poisson_schur_imag' );
execution.error.l2_poisson_schur_real ...
    = h5read( field_file_name, ...
    '/execution/error/l2_poisson_schur_real' );
execution.error.l2_poisson_schur_kernel ...
    = h5read( field_file_name, ...
    '/execution/error/l2_poisson_schur_kernel' );
execution.error.linf_diffusion_imag ...
    = h5read( field_file_name, ...
    '/execution/error/linf_diffusion_imag' );
execution.error.linf_diffusion_real ...
    = h5read( field_file_name, ...
    '/execution/error/linf_diffusion_real' );
execution.error.linf_divergence ...
    = h5read( field_file_name, ...
    '/execution/error/linf_divergence' );
execution.error.linf_viscous_imag ...
    = h5read( field_file_name, ...
    '/execution/error/linf_viscous_imag' );
execution.error.linf_viscous_real ...
    = h5read( field_file_name, ...
    '/execution/error/linf_viscous_real' );
execution.error.total_norm_numeric_error ...
    = h5read( field_file_name, ...
    '/execution/error/total_norm_numeric_error' );

% Read WallTime-related data
execution.wall_time.field_io   = h5read( field_file_name, ...
    '/execution/wall_time/field_io' );
execution.wall_time.restart_io = h5read( field_file_name, ...
    '/execution/wall_time/restart_io' );
execution.wall_time.null_basis = h5read( field_file_name, ...
    '/execution/wall_time/null_basis' );
execution.wall_time.null_error = h5read( field_file_name, ...
    '/execution/wall_time/null_error' );
execution.wall_time.setup = h5read( field_file_name, ...
    '/execution/wall_time/setup' );
execution.wall_time.solve_diffusion = h5read( field_file_name, ...
    '/execution/wall_time/solve_diffusion' );
execution.wall_time.solve_poisson = h5read( field_file_name, ...
    '/execution/wall_time/solve_poisson' );
execution.wall_time.solve_viscous = h5read( field_file_name, ...
    '/execution/wall_time/solve_viscous' );
execution.wall_time.start = h5read( field_file_name, ...
    '/execution/wall_time/start' );
execution.wall_time.steps = h5read( field_file_name, ...
    '/execution/wall_time/steps' );
execution.wall_time.total = h5read( field_file_name, ...
    '/execution/wall_time/total' );

end
