function data = smpm_read_postfile( post_file_name )
% data = smpm_read_postfile( post_file_name[, indexes] )
%
% Reads the contents of the post file generated by the SMPM post processing
% code.
%
% Takes 1 argument:
%
%   post_file_name - String indicating the post file to read from disk.
%
% Returns 1 value:
%
%   data - Structure with fields as described below.
%
%     .grid.x       - Matrix, of size (mz * n) x (mx * n) x my, containing 
%                     the x-coordinates of the mesh associated with the post
%                     variables.
%     .grid.y       - Matrix, of size (mz * n) x (mx * n) x my, containing 
%                     the y-coordinates of the mesh associated with the post
%                     variables.
%     .grid.z       - Matrix, of size (mz * n) x (mx * n) x my, containing 
%                     the z-coordinates of the mesh associated with the post
%                     variables.
%     .post.div     - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the divergence for each grid point.
%     .post.drhodx  - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the derivative of the density in the x-direction.
%     .post.drhody  - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the derivative of the density in the y-direction.
%     .post.drhodz  - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the derivative of the density in the z-direction.
%     .post.dudx    - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the derivative of the u-velocity in the x-direction.
%     .post.dudy    - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the derivative of the u-velocity in the y-direction.
%     .post.dudz    - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the derivative of the u-velocity in the z-direction.
%     .post.dvdx    - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the derivative of the v-velocity in the x-direction.
%     .post.dvdy    - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the derivative of the v-velocity in the y-direction.
%     .post.dvdz    - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the derivative of the v-velocity in the z-direction.
%     .post.dwdx    - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the derivative of the w-velocity in the x-direction.
%     .post.dwdy    - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the derivative of the w-velocity in the y-direction.
%     .post.dwdz    - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the derivative of the w-velocity in the z-direction.
%     .post.ens     - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the enstrophy for each grid point.
%     .post.kin_ene - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the kinetic energy for each grid point.
%     .post.omega_x - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the x-component of vorticity for each grid point.
%     .post.omega_y - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the y-component of vorticity for each grid point.
%     .post.omega_z - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the z-component of vorticity for each grid point.
%     .post.rho     - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the density for each grid point.
%     .post.rho_bar - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the background density for each grid point.
%     .post.stream  - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the streamfunction for each grid point.
%     .post.ux      - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the velocity in the x-direction for each grid point.
%     .post.uy      - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the velocity y-direction for each grid point.
%     .post.uz      - Matrix, of size (mz * n) x (mx * n) x my, containing
%                     the velocity z-direction for each grid point.

% Read the grid information and the grid.
data.grid.n  = h5read( post_file_name, '/grid/n' );
data.grid.mx = h5read( post_file_name, '/grid/mx' );
data.grid.my = h5read( post_file_name, '/grid/my' );
data.grid.mz = h5read( post_file_name, '/grid/mz' );
data.grid.x  = h5read( post_file_name, '/grid/x' );
data.grid.y  = h5read( post_file_name, '/grid/y' );
data.grid.z  = h5read( post_file_name, '/grid/z' );

% Read the post-processed field
data.post.div            = h5read( post_file_name, '/post/div' );
data.post.drhodx         = h5read( post_file_name, '/post/drhodx' );
data.post.drhody         = h5read( post_file_name, '/post/drhody' );
data.post.drhodz         = h5read( post_file_name, '/post/drhodz' );
data.post.dudx           = h5read( post_file_name, '/post/dudx' );
data.post.dudy           = h5read( post_file_name, '/post/dudy' );
data.post.dudz           = h5read( post_file_name, '/post/dudz' );
data.post.dvdx           = h5read( post_file_name, '/post/dvdx' );
data.post.dvdy           = h5read( post_file_name, '/post/dvdy' );
data.post.dvdz           = h5read( post_file_name, '/post/dvdz' );
data.post.dwdx           = h5read( post_file_name, '/post/dwdx' );
data.post.dwdy           = h5read( post_file_name, '/post/dwdy' );
data.post.dwdz           = h5read( post_file_name, '/post/dwdz' );
data.post.enstrophy      = h5read( post_file_name, '/post/enstrophy' );
data.post.kinetic_energy = h5read( post_file_name, '/post/kinetic_energy' );
data.post.omega_x        = h5read( post_file_name, '/post/omega_x' );
data.post.omega_y        = h5read( post_file_name, '/post/omega_y' );
data.post.omega_z        = h5read( post_file_name, '/post/omega_z' );
data.post.rho            = h5read( post_file_name, '/post/rho' );
data.post.rho_bar        = h5read( post_file_name, '/post/rho_bar' );
data.post.stream         = h5read( post_file_name, '/post/stream' );
data.post.ux             = h5read( post_file_name, '/post/ux' );
data.post.uy             = h5read( post_file_name, '/post/uy' );
data.post.uz             = h5read( post_file_name, '/post/uz' );


end
